package br.unisinos.hefestos.provider;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.os.Build;
import android.util.Log;

import br.unisinos.hefestos.utility.LogUtils;

public class HefestosDbHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME = "Hefestos.db";

    private static final int VER_DEVELOPMENT = 1;
    private static final int CUR_DATABASE_VERSION = VER_DEVELOPMENT;
    private static final String LOG_TAG = LogUtils.makeLogTag(HefestosDbHelper.class);

    private final Context mContext;

    public HefestosDbHelper(Context context) {
        super(context, DATABASE_NAME, null, CUR_DATABASE_VERSION);
        mContext = context;
    }

    @Override
    public void onConfigure(SQLiteDatabase db){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            db.setForeignKeyConstraintsEnabled(true);
        } else {
            db.execSQL("PRAGMA foreign_keys=ON;");
        }
        super.onConfigure(db);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {

        final String SQL_CREATE_USER = HefestosContract.CREATE_TABLE + HefestosContract.Tables.USER + " (" +
                HefestosContract.User._ID + HefestosContract.PRIMARY_KEY + ", " +
                HefestosContract.User.EXTERNAL_ID + HefestosContract.TYPE_TEXT + HefestosContract.NULL +
                "); ";

        final String SQL_CREATE_RESOURCE_TABLE = HefestosContract.CREATE_TABLE + HefestosContract.Tables.RESOURCE + " (" +
                HefestosContract.Resource._ID + HefestosContract.PRIMARY_KEY + " ," +
                HefestosContract.Resource.TYPE + HefestosContract.TYPE_INTEGER + HefestosContract.NOT_NULL + ", " +
                HefestosContract.Resource.NAME + HefestosContract.TYPE_TEXT + HefestosContract.NOT_NULL + ", " +
                HefestosContract.Resource.EXTERNAL_ID + HefestosContract.TYPE_TEXT + HefestosContract.NOT_NULL + ", " +
                HefestosContract.Resource.DESCRIPTION + HefestosContract.TYPE_TEXT + HefestosContract.NULL + ", " +
                HefestosContract.Resource.LATITUDE + HefestosContract.TYPE_REAL + HefestosContract.NULL + ", " +
                HefestosContract.Resource.LONGITUDE + HefestosContract.TYPE_REAL + HefestosContract.NULL + "); ";

        final String SQL_CREATE_TAG = HefestosContract.CREATE_TABLE + HefestosContract.Tables.TAG + " (" +
                HefestosContract.Tag._ID + HefestosContract.PRIMARY_KEY + ", " +
                HefestosContract.Tag.EXTERNAL_ID + HefestosContract.TYPE_TEXT + HefestosContract.NOT_NULL + ", " +
                HefestosContract.Tag.CODE + HefestosContract.TYPE_TEXT + HefestosContract.NOT_NULL + ", " +
                HefestosContract.PTrail.RESOURCE_ID + HefestosContract.TYPE_INTEGER + HefestosContract.NOT_NULL + ", " +
                " FOREIGN KEY (" + HefestosContract.Tag.RESOURCE_ID + ") " + HefestosContract.References.RESOURCE_ID + "); ";

        final String SQL_CREATE_PTRAIL = HefestosContract.CREATE_TABLE + HefestosContract.Tables.PTRAIL + " (" +
                HefestosContract.PTrail._ID + HefestosContract.PRIMARY_KEY + " ," +
                HefestosContract.PTrail.RESOURCE_ID + HefestosContract.TYPE_INTEGER + HefestosContract.NOT_NULL + ", " +
                HefestosContract.PTrail.DATE_TIME + HefestosContract.TYPE_INTEGER + HefestosContract.NOT_NULL + ", " +
                HefestosContract.PTrail.USER_ID + HefestosContract.TYPE_INTEGER + HefestosContract.NOT_NULL + ", " +
                " FOREIGN KEY (" + HefestosContract.PTrail.USER_ID + ") " + HefestosContract.References.USER_ID  +
                " FOREIGN KEY (" + HefestosContract.PTrail.RESOURCE_ID + ") " + HefestosContract.References.RESOURCE_ID + "); ";


        Log.v(LOG_TAG, "vai rodar criações de tabela");

        // Resources de teste
        db.execSQL(SQL_CREATE_USER);
        db.execSQL(SQL_CREATE_RESOURCE_TABLE);
        db.execSQL(SQL_CREATE_TAG);
        db.execSQL(SQL_CREATE_PTRAIL);

        Log.v(LOG_TAG, "criou tabelas, vai inserir coisas");

        // Insere usuáiro padrão
        db.execSQL("INSERT INTO " + HefestosContract.Tables.USER + "(" + HefestosContract.User.EXTERNAL_ID + ") VALUES (1);");


        // TODO recursos de teste APAGAR
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (1,'recurso 1','1',-30.0202978,-51.1641586);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (1,'recurso 2','2',-30.0202893, -51.1641447);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (1,'recurso 3','3',-30.0202425, -51.1641845);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (1,'recurso 4','4',-30.0204, -51.1640341);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (1,'recurso 5','5',-30.0199855, -51.164333);");


        //Insere recursos externos

        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Alimentação','Cantina Happy Station - Centro 6','2',-29.793158333333334,-51.151913666666665	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Central de Relacionamento SafePark - Centro 6','3',-29.793603333333333,-51.15181016666667	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Lacomp - Centro 6','4',-29.794437333333335,-51.151966333333334	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Alimentação','Lanches do Alemão - Centro 6','5',-29.79498866666667,-51.15222233333334	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Lapro - Centro 6','6',-29.7951955,-51.15220266666667	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Telefone','Telefone Público 6L - Centro 6','7',-29.79522066666667,-51.151763333333335	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Toalete','Toalete Acessível 6M - Centro 6','8',-29.795431833333335,-51.15170450000001	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Auditoria 6O - Centro 6','9',-29.795912166666668,-51.151636333333336	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Posto de Atendimento 6P - Centro 6','10',29.796232833333338,-51.15150533333334	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Telefone','Telefone Público 6P - Centro 6','11',-29.7962345,-51.15155766666667	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Elevador','Elevador do prédio 6B - Centro 6','12',-29.793147166666667,-51.15263166666667	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Rampa','Rampa de Acesso ao Prédio 6A - Centro 6','13',-29.793087500000002,-51.151952	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Telefone','Telefone Público 6C - Centro 6','14',-29.793273833333334,-51.15180983333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Toalete','Toalete com Acessibilidade Happy Station - Centro 6','15',-29.793192999999995,-51.15172316666667	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento Bancário','Terminal de Autoatendimento Bancário','16',-29.79308,-51.15172883333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Ambiente de Relacionamento (AR) - Centro 6','17',-29.793644499999996,-51.151867666666675	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Toalete','Toalete Acessível (AR) - Centro 6','18',-29.7938115,-51.15172883333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Serviços de Impressão - Centro 6','19',-29.793899333333336,-51.151838500000004	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Telefone','Telefone Público 6E - Centro 6','20',-29.79355966666667,-51.151865	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Painel Diretório do Campos - Centro 6','21',-29.793041833333337,-51.15229033333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Vaga de estacionamento','Estacionamento para Ambulância - Centro 6','22',-29.792990999999997,-51.152770499999995	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Telefone','Telefone Público 6B - Centro 6','23',-29.793431499999997,-51.152637999999996	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Ponto Crítico','Escada 6P - Centro 6','24',-29.79631283333333,-51.15150116666667	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Alimentação','Sabor de Açaí - Redondo','25',-29.794765166666668,-51.154883500000004	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Alimentação','RU Restaurante Universitário - Redondo','26',-29.7944745,-51.155055499999996	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento Bancário','Banco do Brasil - Redondo','27',-29.79449383333333,-51.15527583333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Central de Relacionamento SafePark - Redondo','28',-29.79457016666667,-51.15546433333334	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Farmácias','Agarfarma Farmácias - Redondo','29',-29.795073166666665,-51.155251666666665	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Ponto Crítico','Escada - Redondo','30',-29.79508466666667,-51.15522333333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento','Atendimento Unisinos - Biblioteca','31',-29.79503216666667,-51.15508833333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Lojas','Cultural Store - Bilioteca','32',-29.79499483333333,-51.15655266666666	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Alimentação','Letras e Sabores - Biblioteca','33',-29.794999,-51.156561499999995	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Elevador','Elevador - Biblioteca','34',-29.79520433333333,-51.156334666666666	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Toalete','Toalete Acessível no 5º Andar - Biblioteca','35',-29.79517733333333,-51.156508833333326	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Auditórios','Auditório Central - Centro 6','36',-29.79371383333333,-51.15347783333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Vaga de Estacionamento','Vaga de Estacionamento - Centro 6','37',-29.79273722483273,-51.15205527926774	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Rampa','Rampa de Entrada Portão B','38',-29.79230594791655,-51.15448230703053	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Painel Informativo','Painel Informativo Entrada do Portão B','39',-29.79230594791656,-51.15448230703054	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Telefone','Telefone Acessível Centro 1','40',-29.792453977487092,-51.15478076725516	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Happy Station','Happy Station Centro 1','41',-29.792526300842642,-51.15484149715774	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Toalete','Toalete Acessível Centro 1','42',-29.792810277946174,-51.15446688169749	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Maquina de Café','Máquina de Café do Centro 6','43',-29.792995875808902,-51.15440880911482	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Ponto Crítico','Ponto Crítico Escada do Centro 6','44',-29.79343138336407,-51.152718543661614	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Atendimento Bancario','Atm Santander do Centro 1','45',-29.79354982538818,-51.1544096119377	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Auditórios','Auditório Central - Centro 6','46',-29.79371383333333,-51.15347783333333	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'coordenadas','teste com nova forma de buscar coordenadas','63',-30.0205155,-51.1640837	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'parada','parada circular unisinos','65',-29.7923075,-51.1547197	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'parada','parada entrada topo','66',-29.7930871,-51.1508177	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'parada','2','69',-29.796104,-51.1525275	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'porta c01','acesso','73',-29.7931361,-51.1527121	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'mobilab','mb','74',-29.7926553,-51.1528163	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ", " + HefestosContract.Resource.LATITUDE+ ", " + HefestosContract.Resource.LONGITUDE + ") VALUES (0, 	'Porta Frente','Porta C02','76',-29.793118203321328,-51.152594825228775	);");


        // Insere recursos internos
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Prédio 6B','Centro 6 Bloco B','1'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório de Análise de Alimentos','2'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório de Microbiologia','3'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Elevador','Elevador','4'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Toalete','Toalete do primeiro piso','5'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Pavimento','Subsolo','6'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Pavimento','Pavimento 1º andar do 6B','7'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Pavimento','Pavimento 2º andar do 6B','8'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Pavimento','Pavimento 3º andar do 6B','9'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Pavimento','Pavimento 4º andar do 6B','10'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Toalete','Toalete do 2º Pavimento','11'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Acesso 6A','Acesso ao prédio 6A','12'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Corredor','Corredor do 2º Pavimento','13'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Secretaria','Secretaria','14'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Coordenação','Coordenação das Graduações Tecnológicas','15'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório de Engenharia','16'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Elevador','Elevador','17'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório Geoquímica','18'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Maclab','Laboratório Maclab','19'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Mobilab','Laboratório Mobilab','20'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Servidor','Servidor do Projeto Hefestos','21'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Mesa','Mesa de Reuniões','22'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Armário','Armário de Dispositivos','23'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Elevador','Elevador','24'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Acesso Salas','Acesso à Salas','25'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Acesso Gabinetes','Acesso aos Gabinetes','26'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Sala dos Seminários','Sala dos Seminários','27'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Salas de Reuniões','Salas de Reuniões','28'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório de Computação Gráfica','29'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Coordenação','Coordenação Pós-Graduação','30'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório de Engenharia de Software','31'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Gabinete','Gabinete do Professor Barbosa','32'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Laboratório','Laboratório de Informática Geral','33'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Convivência','Sala de Convivência','34'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Toalete','Toalete','35'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Diretório de Arquivos','Diretório de Arquivos','36'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Professor','Professor Barbosa','37'	);");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.RESOURCE + "(" + HefestosContract.Resource.TYPE + ", " + HefestosContract.Resource.NAME + ", " + HefestosContract.Resource.DESCRIPTION + ", " + HefestosContract.Resource.EXTERNAL_ID + ") VALUES (1,	'Professor','Professor Kleiner','38'	);");

        // Insere tags

        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'1','17830284',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'2','16436774',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'3','16436111',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'4','17830285',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'5','17705697',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'6','17705696',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'7','17828976',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'8','17830283',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'9','21544284',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'1'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'10','15711272',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'11','14747488',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'12','15719912',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'13','15126573',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'14','14852338',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'15','15721438',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'16','14852337',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'17','14747485',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'18','15719913',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'4'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'19','14747482',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'20','14747483',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'21','14747484',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'22','15320458',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'23','14747486',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'24','14747490',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'25','14848694',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'26','15127884',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'27','14852339',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'8'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'28','14747492',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'29','14747494',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'30','14842759',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'31','14860178',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'32','15719463',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'33','15721569',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'34','15128090',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'35','14849831',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'36','14747498',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'12'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'37','15127953',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'38','14848320',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'39','14848324',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'40','15127886',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'41','14852293',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'42','15719462',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'43','15719460',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'44','14852425',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'45','14850961',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'13'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'46','14848371',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'47','15127667',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'48','14750367',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'49','15127916',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'50','15127915',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'51','15127664',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'52','14852426',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'53','15711271',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'54','14750364',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'20'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'55','15127666',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'56','14750366',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'57','14848722',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'58','14750362',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'59','14848485',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'60','14848323',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'61','17828975',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'62','14848486',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'63','15127640',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'10'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'64','14848326',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'65','14750243',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'66','14750240',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'67','14747491',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'68','14750247',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'69','14747487',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'70','15711269',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'71','14852422',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'72','14848719',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'25'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'73','14848718',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'74','15127955',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'75','15127954',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'76','15711270',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'77','15127665',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'78','14848717',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'79','15127958',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'80','15127885',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'81','15127887',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'26'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'82','15719461',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'83','15127827',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'84','14860184',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'85','14747496',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'86','14747493',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'87','15128089',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'88','14848695',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'89','14747495',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");
        db.execSQL("INSERT INTO " + HefestosContract.Tables.TAG + "(" + HefestosContract.Tag.EXTERNAL_ID + ", " + HefestosContract.Tag.CODE + ", " + HefestosContract.Tag.RESOURCE_ID + ") SELECT 	'90','15320457',	" + HefestosContract.Resource._ID + " FROM " + HefestosContract.Tables.RESOURCE + " WHERE " + HefestosContract.Resource.TYPE + " = 1 AND " + HefestosContract.Resource.EXTERNAL_ID + " = 	'32'	;");

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {




    }
}
